### ISSUE TITLE
enabling dwarfvet causes game to crash

### ISSUE THREAD

**Issue by bessgeor** [NCommander/dfhack-dwarfvet#2]
### Software in use
- PyLNP win x64 0.13
- DF 0.44.09
- DFHACK 0.44.09-r1 (release) on x86-64
- TWBT 6.41

### Problem
Running `dwarfvet enable` causes the game to crash after some ticks.

### Steps to reproduce
Download [my save](https://files.fm/f/x9rjfnq9), run it, run `dwarfvet enable`, wait a couple of seconds.

**Comment by lethosor** [comment]
This should probably be reported in the main DFHack repo.

**Comment by bessgeor** [comment]
OK, thx
